# Generate src/gyre/nn/unicode_cat.inc for tiktoken V1 pretok (\\p{L} \\p{N} \\s).
# Run: py -3 scripts/gen_unicode_cat.py

from __future__ import annotations

import pathlib
import unicodedata

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "src" / "gyre" / "nn" / "unicode_cat.inc"


def cat(cp: int) -> str:
    try:
        return unicodedata.category(chr(cp))
    except ValueError:
        return "Cn"


def ranges(pred) -> list[tuple[int, int]]:
    rs: list[tuple[int, int]] = []
    start = prev = None
    for cp in range(0x110000):
        if pred(cp):
            if start is None:
                start = prev = cp
            elif cp == prev + 1:
                prev = cp
            else:
                rs.append((start, prev))
                start = prev = cp
    if start is not None:
        rs.append((start, prev))
    return rs


def is_letter(cp: int) -> bool:
    return cat(cp).startswith("L")


def is_number(cp: int) -> bool:
    return cat(cp).startswith("N")


def is_space(cp: int) -> bool:
    if cp in (0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x20, 0x85, 0xA0, 0x1680, 0x2028, 0x2029):
        return True
    return cat(cp) in ("Zs", "Zl", "Zp")


def emit(name: str, rs: list[tuple[int, int]]) -> str:
    lines = [f"static constexpr std::uint32_t {name}[][2] = {{"]
    for a, b in rs:
        lines.append(f"  {{{a:#x}, {b:#x}}},")
    lines.append("};")
    lines.append(f"static constexpr int {name}_n = {len(rs)};")
    return "\n".join(lines)


def main() -> None:
    parts = [
        "// Generated by scripts/gen_unicode_cat.py — Unicode letter/number/space for tiktoken V1."
    ]
    parts.append(emit("kLuL", ranges(is_letter)))
    parts.append(emit("kNuN", ranges(is_number)))
    parts.append(emit("kSp", ranges(is_space)))
    OUT.write_text("\n\n".join(parts) + "\n", encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
